project:
  type: website

website:
  title: "Home ğŸ¡"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/arinbaruah
      - icon: linkedin
        href: https://www.linkedin.com/in/arindam-baruah/
format:
  html:
    theme: 
      - sandstone
      - style.scss
    toc: false

editor: source

