project:
  type: website
  resources: 
    cv/Aaron_Baruah-32779267-Resume.pdf

website:
  title: "R-insights ğŸ“ŠğŸ“ˆğŸ–¥ï¸"
  sidebar: false
  site-url: htt
  repo-url: https://github.com/arinbaruah
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: posts/index.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/arinbaruah
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/arindam-baruah/
        aria-label: LinkedIn

format:
  html:
    theme: 
      - journal
      - style.scss
    toc: false

editor: source


